id: templetonworldcharityfoundationtwcf
name: Templeton World Charity Foundation
abbr: TWCF
plan_s: 2021-01-01
apc:
  tj: true # implementation roadmap
routes:
  self_archiving:
    rights_retention: 2100-01-01  # implementation roadmap