compliant: Yes, the journal policy allows compliance with the Horizon Europe open access mandate
non_compliant: No, the journal policy does not allow compliance with the Horizon Europe open access mandate