id: unitedkingdomresearchinnovationukri
name: UK Research and Innovation.
abbr: UKRI
aka:
  - name: Arts and Humanities Research Council
    abbr: AHRC (UKRI)
  - name: Biotechnology and Biological Sciences Research Council
    abbr: BBSRC (UKRI)
  - name: Economic and Social Research Council
    abbr: ESRC (UKRI)
  - name: Engineering and Physical Sciences Research Council
    abbr: EPSRC (UKRI)
  - name: Innovate UK
    abbr: UKRI
  - name: Medical Research Council
    abbr: MRC (UKRI)
  - name: Natural Environment Research Council
    abbr: NERC (UKRI)
  - name: National Centre for the Replacement Refinement & Reduction of Animals in Research
    abbr: NC3Rs (UKRI)
  - name: Research England
    abbr: UKRI
  - name: Science and Technology Facilities Council
    abbr: STFC (UKRI)
plan_s: 2022-01-01 # Awaiting outcome of OA review
apc:
  tj: false # Awaiting outcome of OA review
routes:
  self_archiving:
    rights_retention: 2100-01-01
  hybrid:
    calculate: true
card_order:
  - tile2
  - tile2_aq
  - tile1
  - tile1_by_exception
  - tile6
  - tile7
  - tile5
  - tile3
  - tile4
cards:
  # Card to display if the Journal is Fully Open Access
  - id: tile1   # derived from fully_oa
    compliant: true
    match_routes:
      must:
        - fully_oa  # The rules for tile1 also say "and allows SA" but all Fully OA journals do, so no need for that route check
    match_qualifications:
      not:
        - fully_oa.oa_exception_caveat
    preferred: false

  - id: tile1_by_exception   # derived from fully_oa
    compliant: true
    match_routes:
      must:
        - fully_oa  # The rules for tile1 also say "and allows SA" but all Fully OA journals do, so no need for that route check
    match_qualifications:
      must:
        - fully_oa.oa_exception_caveat
    preferred: false

  # Transformative Agreements tiles (with and without author qualifications)
  - id: tile2    # derived from ta
    compliant: true
    match_routes:
      must:
        - ta
    match_qualifications:
      not:
        - ta.corresponding_authors
    preferred: false

  - id: tile2_aq     # derived from ta_aq
    compliant: true
    match_routes:
      must:
        - ta
    match_qualifications:
      must:
        - ta.corresponding_authors
    preferred: false

  - id: tile4   # Route 2 (UKRI's version of RR)
    compliant: true
    match_routes:
      not:
        - fully_oa
        - ta
        - tj
        - self_archiving
    preferred: false

  # Transformative Journals tile
  - id: tile6      # derived from tj
    compliant: true
    match_routes:
      must:
        - tj
    preferred: false
    modal: tj

  # Self-Archiving route, only displayed alongside TJ tile
  - id: tile5
    compliant: true
    match_routes:
      must:
        - self_archiving
      not:
        - fully_oa
    preferred: false

  - id: tile7
    compliant: true
    match_routes:
      must:
        - hybrid
      not:
        - tj
        - ta
        - fully_oa
    preferred: false

  # Set of cards to display if there are no compliant results
  - id: tile3
    compliant: false
    match_routes:
      not:
        - fully_oa
        - ta
        - tj
        - hybrid
        - self_archiving
    preferred: false


