compliant: Les options de publication ci-dessous sont conformes à la politique de libre accès de votre organisme de financement
non_compliant: Il n’y a pas d’option de publication conforme à la politique de libre accès de votre organisme de financement
preferred: <a href="#" class="modal-trigger" data-modal="preferred">Voie privilégiée</a>
card_modal: Plus d’informations