id: researchcouncilofnorwayrcn
name: Research Council of Norway
abbr: RCN
plan_s: 2021-01-01
apc:
  tj: true # implementation roadmap
routes:
  self_archiving:
    rights_retention: 2021-01-01  # implementation roadmap