id: aligningscienceacrossparkinsonsasap
name: Aligning Science Across Parkinson's
abbr: ASAP
plan_s: 2022-01-01
apc:
  tj: true # implementation roadmap
routes:
  self_archiving:
    rights_retention: 2021-01-01  # implementation roadmap