[en]
    languageName = "English"
    weight = 1
[fr]
    languageCode = "fr"
    languageName = "Français"
    title="Outil pour vérifier les revues"
    weight = 2
    [fr.params]
        [fr.params.header]
            pageTitle = "Outil pour vérifier les revues"
        [fr.params.text]
            feedbackButton = "Faites-nous part de vos commentaires"
            alert = "L’information fournie par l'outil de vérification des revues représente la compréhension actuelle de la cOAlition S en ce qui concerne les politiques des revues qu'il contient. Nous nous efforcerons de les maintenir à jour et exactes, mais nous n'acceptons aucune responsabilité en cas d'erreurs ou d'omissions"
            comingSoon = "Coming Soon"
        [fr.params.footer]
            address = '''
            cOAlition S Office<br/>
            European Science Foundation<br/>
            1, quai Lezay – Marnésia<br/>
            67080 Strasbourg – France
            '''
            licenseText = "Le contenu sur ce site est régi par une licence"
            licenseUrl = "https://creativecommons.org/licenses/by/4.0/"
            licenseName = "Attribution 4.0 International (CC BY) de Creative Commons"
        [fr.params.results]
            restartButton = "Recommencer"
            printButton = "Imprimer"
            shareButton = "Partager le résultat"
    [fr.menu]
        [[fr.menu.main]]
            name = "Revues&nbsp;en&nbsp;transformation"
            url = "/transformative-journals"
            weight = 1
        [[fr.menu.main]]
            name = "Ententes&nbsp;de&nbsp;transformation"
            pre = " • "
            url = "/transformative-agreements"
            weight = 2
        [[fr.menu.main]]
            name = "Listes&nbsp;d’exceptions"
            pre = " • "
            url = "/exception-lists"
            weight = 3
        [[fr.menu.main]]
            name = "Journals&nbsp;participating&nbsp;in&nbsp;JCS"
            pre = " • "
            url = "/jcs"
            weight = 4
        [[fr.menu.main]]
            name = "Documentation&nbsp;API"
            pre = " • "
            url = "/apidocs"
            weight = 5
        [[fr.menu.main]]
            name = "Widget&nbsp;intégrable"
            pre = " • "
            url = "/widget"
            weight = 6
        [[fr.menu.main]]
            name = "FAQ"
            url = "/faq"
            weight = 7
        [[fr.menu.main]]
            pre = " • "
            name = "Avis&nbsp;de&nbsp;confidentialité"
            url = "/notices#privacy_notice"
            weight = 8
        [[fr.menu.main]]
            name = "Avis&nbsp;de&nbsp;non-responsabilité&nbsp;et&nbsp;droits&nbsp;d’auteur"
            pre = " • "
            url = "/notices#disclaimer_and_copyright"
            weight = 9
        [[fr.menu.main]]
            name = "Acknowledgements"
            pre = " • "
            url = "/acknowledgements"
            weight = 10
        [[fr.menu.main]]
            name = "Historique&nbsp;des&nbsp;versions"
            pre = " • "
            url = "/release-history"
            weight = 11