[[main]]
    name = "Transformative&nbsp;Journals"
    url = "/transformative-journals"
    weight = 1
[[main]]
    name = "Transformative&nbsp;Agreements"
    pre = " • "
    url = "/transformative-agreements"
    weight = 2
[[main]]
    name = "Exception&nbsp;Lists"
    pre = " • "
    url = "/exception-lists"
    weight = 3
[[main]]
    name = "Price&nbsp;Data&nbsp;Providers"
    pre = " • "
    url = "/jcs"
    weight = 4
[[main]]
    name = "API&nbsp;Documentation"
    pre = " • "
    url = "/apidocs"
    weight = 5
[[main]]
    name = "Embeddable&nbsp;Widget"
    pre = " • "
    url = "/widget"
    weight = 6
[[main]]
    name = "FAQ"
    url = "/faq"
    weight = 7
[[main]]
    pre = " • "
    name = "Privacy&nbsp;Notice"
    url = "/notices#privacy_notice"
    weight = 8
[[main]]
    name = "Disclaimer&nbsp;&&nbsp;Copyright"
    pre = " • "
    url = "/notices#disclaimer_and_copyright"
    weight = 9
[[main]]
    name = "Acknowledgements"
    pre = " • "
    url = "/acknowledgements"
    weight = 10
[[main]]
    name = "Release&nbsp;History"
    pre = " • "
    url = "/release-history"
    weight = 11