id: howardhughesmedicalinstitutehhmi
name: Howard Hughes Medical Institute
abbr: HHMI
plan_s: 2022-01-01
apc:
  tj: true # implementation roadmap
routes:
  self_archiving:
    rights_retention: 2021-01-01  # implementation roadmap