id: nationalinstitutefornuclearphysicsinfnitaly
name: National Institute for Nuclear Physics
abbr: INFN
country: Italy
plan_s: 2021-01-01
apc:
  tj: true # implementation roadmap
routes:
  self_archiving:
    rights_retention: 2100-01-01  # implementation roadmap