id: netherlandsorganisationforscientificresearchnwo
name: Netherlands Organisation for Scientific Research
abbr: NWO
plan_s: 2021-01-01
apc:
  tj: false # implementation roadmap
routes:
  self_archiving:
    rights_retention: 2021-01-01  # implementation roadmap